// Job handlers for AI/offline script generation and per-scene revision.
import { AppError } from '../lib/errors.js';

export function briefFromProject(p, body = {}) {
  return {
    title: p.title, category: p.category, language: p.language, ageMin: p.age_min, ageMax: p.age_max,
    targetDurationSec: p.target_duration_sec, topic: body.topic ?? p.topic, visualStyle: p.visual_style, narrationStyle: p.narration_style,
    difficulty: p.difficulty, format: p.format, kit: body.kit, characters: body.characters, itemCount: body.itemCount, notes: body.notes, noBookends: body.noBookends,
    syntheticVoice: true,
  };
}

export function registerGenerationJobs(ctx) {
  const { jobs, llm, projects, costs } = ctx;
  /** A reservation is released if the provider was never billed; settled at real usage if tokens were consumed. */
  const releaseCost = (costId, e, provider) => {
    if (!costId) return;
    if (e.usage?.inputTokens || e.usage?.outputTokens) costs.settle(costId, costs.estimate({ kind: 'llm', provider, model: e.model, ...e.usage }).estimateUsd);
    else costs.settle(costId, 0, 'estimate');
  };

  jobs.register('generate_package', async ({ job, signal, log, progress }) => {
    const { projectId, provider, brief, costEstimate, userId } = job.payload;
    const proj = projects.must(projectId);
    if (proj.package.scenes?.length) { const v = projects.snapshot(projectId, 'Before regeneration', userId); log('info', `Snapshotted existing package as v${v}`); }
    progress(0.1, `Generating with ${provider}…`);
    log('info', `Generating package (${provider}) for "${proj.title}"`);
    const costId = costEstimate?.estimateUsd > 0 ? costs.record({ projectId, jobId: job.id, provider, operation: 'llm.generate_package', est: costEstimate, units: costEstimate.breakdown?.outputTokens, unit: 'tokens', note: 'estimate' }) : null;
    let out;
    try { out = await llm.generatePackage(brief, { provider, signal }); } catch (e) { releaseCost(costId, e, provider); throw e; }
    if (costId && out.usage.outputTokens) {
      const actual = costs.estimate({ kind: 'llm', provider, model: out.model, inputTokens: out.usage.inputTokens, outputTokens: out.usage.outputTokens });
      costs.settle(costId, actual.estimateUsd);
      log('info', `Token usage: ${out.usage.inputTokens} in / ${out.usage.outputTokens} out ≈ $${actual.estimateUsd}`);
    }
    progress(0.8, 'Saving package…');
    projects.savePackage(projectId, out.pkg, { snap: true, label: `Generated by ${provider}${out.model ? ` (${out.model})` : ''}`, userId });
    projects.setStatus(projectId, 'scripted');
    log('info', `Saved ${out.pkg.scenes.length} scenes`);
    return { scenes: out.pkg.scenes.length, provider, model: out.model };
  }, { lane: 'llm', maxAttempts: 3 });

  jobs.register('revise_scene', async ({ job, signal, log, progress }) => {
    const { projectId, sceneId, instruction, provider, costEstimate, userId } = job.payload;
    const proj = projects.must(projectId);
    const scene = proj.package.scenes.find((s) => s.id === sceneId);
    if (!scene) throw new AppError(404, 'NOT_FOUND', 'Scene no longer exists.');
    if (scene.locked) throw new AppError(409, 'SCENE_LOCKED', 'This scene is locked. Unlock it before AI revision.');
    progress(0.2, 'Revising scene…');
    const costId = costEstimate?.estimateUsd > 0 ? costs.record({ projectId, jobId: job.id, provider, operation: 'llm.revise_scene', est: costEstimate, units: costEstimate.breakdown?.outputTokens, unit: 'tokens' }) : null;
    let out;
    try { out = await llm.reviseScene(proj.package, sceneId, instruction, { provider, signal }); } catch (e) { releaseCost(costId, e, provider); throw e; }
    if (costId && out.usage.outputTokens) costs.settle(costId, costs.estimate({ kind: 'llm', provider, model: out.model, inputTokens: out.usage.inputTokens, outputTokens: out.usage.outputTokens }).estimateUsd);
    projects.replaceScene(projectId, sceneId, out.scene, `Before AI revision of "${scene.title}"`, userId);
    log('info', `Scene "${scene.title}" revised (previous state saved as a version)`);
    return { sceneId };
  }, { lane: 'llm', maxAttempts: 3 });
}
