import { get, post, api } from '../api.js';
import { h, field, select, toast, fail, badge, lineChart, num, usd, empty, jobPanel, fmtDur } from '../ui.js';

export async function render(root, S) {
  const days = +(sessionStorage.getItem('eak.days') || 28);
  const [sum, prod, yt] = await Promise.all([get(`/api/analytics/summary?days=${days}`), get('/api/analytics/production'), get('/api/youtube/status')]);
  const refresh = () => { root.replaceChildren(); render(root, S); };
  const t = sum.totals; const panel = jobPanel();
  const sync = async () => { try { const r = await post('/api/youtube/analytics/sync', { days }); const j = await panel.track(r.job.id, 'Analytics sync'); if (j?.status === 'succeeded') refresh(); } catch (e) { fail(e); } };
  const csv = h('textarea', { rows: 4, placeholder: 'date,video_id,views,impressions,impressions click-through rate (%)\n2026-10-01,VIDEOID,120,3400,4.1' }); const file = h('input', { type: 'file', accept: '.csv,text/csv', onchange: async (e) => { csv.value = await e.target.files[0].text(); } });
  const card = (label, v, sub) => h('div', { class: 'card stat' }, h('b', {}, v ?? '—'), h('span', {}, label), sub && h('div', { class: 'small muted' }, sub));
  root.append(h('div', { class: 'stack-lg' }, h('div', { class: 'row spread' }, h('h1', {}, '📈 Analytics'), h('div', { class: 'row' }, select([[7, 'Last 7 days'], [28, 'Last 28 days'], [90, 'Last 90 days'], [365, 'Last 365 days']], days, { onchange: (e) => { sessionStorage.setItem('eak.days', e.target.value); refresh(); } }), h('button', { class: 'btn', disabled: !S.can('publish') || !yt.connected, title: yt.connected ? '' : 'Connect YouTube first', onclick: sync }, '↻ Sync from YouTube'), h('a', { class: 'btn', href: '/api/analytics/export.csv' }, '⬇ CSV'))), panel.node,
    h('div', { class: 'callout' }, 'Every number here comes from the YouTube Analytics API or a CSV you imported, and is labelled with its source. ', h('b', {}, 'Nothing is estimated or invented.'), sum.hasData ? ` Sources: ${sum.sources.join(', ')}.` : ''),
    !sum.hasData ? empty('📭', 'No analytics data yet', 'Publish a video and connect YouTube, or import a CSV exported from YouTube Studio.') : h('div', { class: 'stack-lg' },
      h('div', { class: 'grid g4' }, card('Views', num(t.views)), card('Watch time (hours)', t.watchHours ? num(+t.watchHours.toFixed?.(1) ?? t.watchHours) : '—'), card('Avg view duration', sum.averages.averageViewDuration != null ? fmtDur(sum.averages.averageViewDuration) : '—'), card('Subscribers gained', num(t.subscribersGained)), card('Impressions', t.impressions ? num(t.impressions) : '—', 'from manual import'), card('Click-through rate', sum.averages.ctrPercent != null ? `${sum.averages.ctrPercent}%` : '—', 'from manual import'), card('Likes', num(t.likes)), card('Avg % viewed', sum.averages.averageViewPercentage != null ? `${sum.averages.averageViewPercentage}%` : '—')),
      sum.revenue ? h('div', { class: 'card warn' }, h('h2', {}, `Estimated revenue: ${usd(sum.revenue.estimatedUsd)}`), h('p', { class: 'small' }, sum.revenue.label)) : h('div', { class: 'callout small' }, 'Revenue is not shown: it only appears if you granted the revenue-analytics permission on a monetised channel — and even then it is an estimate, not finalised earnings or a payment.'),
      h('div', { class: 'grid g2' }, h('div', { class: 'card' }, h('h2', {}, 'Views per day'), lineChart(sum.daily.filter((d) => d.views != null).map((d) => ({ x: d.date.slice(5), y: d.views })), { label: 'Views per day' })), h('div', { class: 'card' }, h('h2', {}, 'Audience retention'), sum.retention.length ? lineChart(sum.retention.map((r) => ({ x: `${Math.round(r.ratio * 100)}%`, y: Math.round(r.watchRatio * 100) })), { color: '#3CC47C', label: 'Audience retention' }) : h('p', { class: 'muted small' }, 'Retention appears once YouTube reports enough views for a video.'))),
      h('div', { class: 'grid g2' }, h('div', { class: 'card' }, h('h2', {}, 'By topic'), perf(sum.byTopic)), h('div', { class: 'card' }, h('h2', {}, 'By format'), perf(sum.byFormat))),
      h('div', { class: 'card' }, h('h2', {}, 'By video'), sum.videos.length ? h('div', { class: 'table-wrap' }, h('table', {}, h('thead', {}, h('tr', {}, ['Video', 'Views', 'Watch min', 'Subs', 'Avg %'].map((x) => h('th', {}, x)))), h('tbody', {}, sum.videos.map((v) => h('tr', {}, h('td', {}, h('a', { href: `https://www.youtube.com/watch?v=${v.videoId}`, target: '_blank', rel: 'noopener noreferrer' }, v.videoId), v.projectId && h('div', { class: 'small muted', dir: 'auto' }, S.projects.find((p) => p.id === v.projectId)?.title || '')), h('td', {}, num(v.metrics.views)), h('td', {}, num(v.metrics.estimatedMinutesWatched)), h('td', {}, num(v.metrics.subscribersGained)), h('td', {}, v.metrics.averageViewPercentage ?? '—')))))) : h('p', { class: 'muted small' }, 'Per-video rows appear after an upload through this app, or from a CSV with a video_id column.'))),
    h('div', { class: 'card' }, h('h2', {}, 'Import a YouTube Studio CSV'), h('p', { class: 'small muted' }, 'Needed for impressions and click-through rate (not available from the API). Requires a "date" column (YYYY-MM-DD). Rows are labelled “manual_import”.'), h('div', { class: 'stack' }, file, csv, h('div', {}, h('button', { class: 'btn', disabled: !S.can('write'), onclick: async () => { try { const r = await api('POST', '/api/analytics/import', csv.value, { raw: true, headers: { 'content-type': 'text/csv' } }); toast(`${r.rowsImported} values imported`, 'ok'); refresh(); } catch (e) { fail(e); } } }, 'Import')))),
    h('div', { class: 'card' }, h('div', { class: 'row spread' }, h('h2', {}, 'Production time & cost per video'), h('a', { class: 'btn sm', href: '/api/analytics/production.csv' }, '⬇ CSV')), h('div', { class: 'table-wrap' }, h('table', {}, h('thead', {}, h('tr', {}, ['Video', 'Status', 'Machine time', 'Cost', ''].map((x) => h('th', {}, x)))), h('tbody', {}, prod.videos.map((v) => h('tr', {}, h('td', { dir: 'auto' }, v.title), h('td', {}, v.status), h('td', {}, fmtDur(v.machineSeconds)), h('td', {}, usd(v.costUsd, 4)), h('td', {}, v.costUsd ? (v.costVerified ? badge('verified prices', 'ok') : badge('unverified prices', 'warn')) : badge('free', 'neutral'))))))), h('p', { class: 'small muted' }, 'Machine time = time background jobs ran (rendering, narration, generation). Your own editing/review time is not tracked.'))));
}
const perf = (o) => (Object.keys(o).length ? h('table', {}, h('thead', {}, h('tr', {}, ['', 'Videos', 'Views', 'Watch min'].map((x) => h('th', {}, x)))), h('tbody', {}, Object.entries(o).map(([k, v]) => h('tr', {}, h('td', {}, k), h('td', {}, v.videos), h('td', {}, num(v.views)), h('td', {}, num(v.watchMinutes)))))) : h('p', { class: 'muted small' }, 'Needs uploaded videos with data.'));
