import { get } from '../api.js';
import { h, badge } from '../ui.js';

const FILES = [['logo-main.png', 'Main logo'], ['logo-horizontal.png', 'Horizontal logo'], ['logo-mono-navy.png', 'Mono navy'], ['logo-mono-white.png', 'Mono white'], ['profile-800x800.png', 'Profile image 800×800'], ['banner-2560x1440.png', 'YouTube banner 2560×1440']];
const MASCOTS = [['rayyan', 'ريّان — lion cub (host)'], ['nunu', 'نونو — bunny (counting, kindness)'], ['sallouma', 'سلّومة — turtle (nature, habits)'], ['zaqzaq', 'زقزق — chick (songs, sounds)']];

export async function render(root) {
  const pal = await get('/api/registry').then((r) => r.palette);
  const sw = (n, v) => h('div', { class: 'card', style: { padding: 0, overflow: 'hidden' } }, h('div', { style: { background: v, height: '64px' } }), h('div', { style: { padding: '8px' } }, h('b', {}, n), h('div', { class: 'mono' }, v)));
  const templates = ['colors', 'numbers', 'alphabet', 'animals', 'nature', 'story', 'habits', 'shapes', 'songs', 'general'];
  root.append(h('div', { class: 'stack-lg' }, h('h1', {}, '🎨 EA KIDS brand kit'), h('p', { class: 'muted' }, 'Original identity — cheerful, safe and educational. Regenerate every asset with ', h('code', {}, 'npm run build:brand'), '. Full rules: ', h('a', { href: '/brand-assets/BRAND_GUIDELINES.md', target: '_blank', rel: 'noopener' }, 'Brand guidelines'), '.'),
    h('div', { class: 'card' }, h('h2', {}, 'Logos, profile & banner'), h('div', { class: 'grid g3' }, FILES.map(([f, l]) => h('div', { class: 'stack' }, h('div', { style: { background: f.includes('white') ? '#23285B' : '#fff', border: '2px solid var(--line)', borderRadius: '12px', padding: '10px', display: 'grid', placeItems: 'center', minHeight: '160px' } }, h('img', { src: `/brand-assets/${f}`, alt: l, style: { maxWidth: '100%', maxHeight: '200px' } })), h('div', { class: 'row spread' }, h('b', {}, l), h('a', { class: 'btn sm', href: `/brand-assets/${f}`, download: f }, '⬇'))))), h('p', { class: 'small muted' }, 'The banner keeps its key content inside the 1546×423 all-device safe area; the chick and turtle may be cropped on small screens.')),
    h('div', { class: 'card' }, h('h2', {}, 'Palette'), h('div', { class: 'grid g4' }, Object.entries(pal).map(([n, v]) => sw(n, v)))),
    h('div', { class: 'card' }, h('h2', {}, 'Typography (open-licence, bundled)'), h('div', { class: 'grid g3' }, h('div', {}, h('div', { style: { fontFamily: 'Fredoka', fontSize: '2rem', fontWeight: 600 } }, 'EA KIDS'), h('div', { class: 'small muted' }, 'Fredoka — Latin display')), h('div', { dir: 'rtl' }, h('div', { style: { fontFamily: 'Tajawal', fontSize: '2rem', fontWeight: 800 } }, 'أهلًا يا أصدقائي'), h('div', { class: 'small muted' }, 'Tajawal — Arabic body & captions')), h('div', { dir: 'rtl' }, h('div', { style: { fontSize: '2rem', fontWeight: 800 } }, 'نتعلم الألوان'), h('div', { class: 'small muted' }, 'Baloo Bhaijaan 2 — Arabic headlines (renders in thumbnails)')))),
    h('div', { class: 'card' }, h('h2', {}, 'Mascots'), h('div', { class: 'grid g4' }, MASCOTS.map(([s, l]) => h('div', { class: 'stack center' }, h('img', { src: `/brand-assets/mascots/${s}-happy.png`, alt: l, style: { width: '100%', background: '#FFF6E0', borderRadius: '12px', border: '2px solid var(--line)' } }), h('b', { class: 'small', dir: 'auto' }, l), h('div', { class: 'row', style: { justifyContent: 'center' } }, ['wow', 'wink', 'proud'].map((e) => h('img', { src: `/brand-assets/mascots/${s}-${e}.png`, alt: e, style: { width: '48px', borderRadius: '8px', background: '#FFF6E0' } }))))))),
    h('div', { class: 'card' }, h('h2', {}, 'Thumbnail templates'), h('div', { class: 'grid g3' }, templates.map((t) => h('div', { class: 'stack' }, h('img', { src: `/brand-assets/thumbnail-templates/${t}.png`, alt: t, style: { width: '100%', borderRadius: '10px', border: '2px solid var(--line)' } }), badge(t, 'info')))))));
}
