import { get, post, patch } from '../api.js';
import { h, field, toast, fail, badge, modal, empty, fmtDate } from '../ui.js';

export async function render(root, S) {
  const { characters } = await get('/api/characters');
  const refresh = () => { root.replaceChildren(); render(root, S); };
  root.append(h('div', { class: 'stack-lg' }, h('div', { class: 'row spread' }, h('div', {}, h('h1', {}, '🦁 Character library'), h('p', { class: 'muted' }, 'Locked, original characters. Every storyboard scene references these profiles. Any edit creates a new version — earlier versions are kept.')), h('button', { class: 'btn primary', disabled: !S.can('write'), onclick: () => edit(S, null, refresh) }, '＋ New character')),
    characters.length ? h('div', { class: 'grid g2' }, characters.map((c) => h('div', { class: 'card' }, h('div', { class: 'row', style: { alignItems: 'flex-start' } },
      h('div', { class: 'stack', style: { width: '170px' } }, c.references.filter((r) => r.kind).slice(0, 2).map((r) => h('img', { src: `/api/assets/${r.id}/file`, alt: `${c.name_en} reference`, style: { width: '100%', borderRadius: '10px', background: '#FFF6E0', border: '2px solid var(--line)' } })), !c.references.length && h('div', { class: 'empty small' }, 'no reference images')),
      h('div', { class: 'grow stack' }, h('div', { class: 'row spread' }, h('h2', { style: { margin: 0 } }, c.name_ar, ' ', h('span', { class: 'muted' }, c.name_en)), badge(`v${c.version}`, 'info')), h('div', { class: 'small' }, c.species), h('p', { class: 'small', dir: 'auto' }, c.description),
        h('dl', { class: 'kv small' }, h('dt', {}, 'Look'), h('dd', {}, c.features), h('dt', {}, 'Personality'), h('dd', {}, c.personality), h('dt', {}, 'Teaching role'), h('dd', {}, c.edu_role), h('dt', {}, 'Voice'), h('dd', {}, `${c.voice.style || '—'} — ${c.voice.note || ''}`), h('dt', {}, 'Colours'), h('dd', { class: 'row' }, Object.entries(c.colors).map(([k, v]) => h('span', { class: 'row', style: { gap: '4px' } }, h('i', { style: { width: '16px', height: '16px', borderRadius: '4px', background: v, border: '1px solid #0003', display: 'inline-block' } }), k)))),
        h('div', { class: 'row' }, h('button', { class: 'btn sm', disabled: !S.can('write'), onclick: () => edit(S, c, refresh) }, '✏️ Edit'), h('button', { class: 'btn sm', onclick: () => history(c) }, '🕘 Versions'), h('button', { class: 'btn sm', onclick: () => prompts(c) }, '📋 Approved prompts'))))))) : empty('🦁', 'No characters', '')));
}

function field_(label, el) { return field(label, el); }
function edit(S, c, done) {
  const f = { slug: h('input', { value: c?.slug || '', disabled: !!c }), ar: h('input', { dir: 'auto', value: c?.name_ar || '' }), en: h('input', { value: c?.name_en || '' }), species: h('input', { value: c?.species || '' }), desc: h('textarea', { dir: 'auto' }, c?.description || ''), feat: h('textarea', {}, c?.features || ''), pers: h('input', { value: c?.personality || '' }), role: h('input', { value: c?.edu_role || '' }), vnote: h('input', { value: c?.voice?.note || 'Licensed TTS voice or consenting voice actor only.' }), colors: h('input', { value: Object.entries(c?.colors || {}).map(([k, v]) => `${k}=${v}`).join(', '), placeholder: 'body=#FFB84D, scarf=#3FA9F5' }), prompts: h('textarea', {}, (c?.approved_prompts || []).join('\n---\n')) };
  modal((close) => [h('h2', {}, c ? `Edit ${c.name_en} (creates v${c.version + 1})` : 'New character'), h('div', { class: 'stack' }, h('div', { class: 'grid g3' }, !c && field_('Slug (a–z)', f.slug), field_('Name (Arabic)', f.ar), field_('Name (English)', f.en)), field_('Species', f.species), field_('Description', f.desc), field_('Visual features (used in image prompts)', f.feat), h('div', { class: 'grid g2' }, field_('Personality', f.pers), field_('Educational role', f.role)), field_('Colours', f.colors), field_('Voice note (legal)', f.vnote), field_('Approved prompts (separate with ---)', f.prompts),
    h('div', { class: 'callout warn small' }, 'Do not base a character on copyrighted cartoon characters or on a real person’s voice/likeness without written permission.'),
    h('div', { class: 'row', style: { justifyContent: 'flex-end' } }, h('button', { class: 'btn', onclick: close }, 'Cancel'), h('button', { class: 'btn primary', onclick: async () => {
      const body = { nameAr: f.ar.value, nameEn: f.en.value, species: f.species.value, description: f.desc.value, features: f.feat.value, personality: f.pers.value, eduRole: f.role.value, voice: { ...(c?.voice || {}), note: f.vnote.value }, colors: Object.fromEntries(f.colors.value.split(',').map((x) => x.trim().split('=')).filter((x) => x[0] && x[1])), approvedPrompts: f.prompts.value.split('---').map((x) => x.trim()).filter(Boolean) };
      try { c ? await patch(`/api/characters/${c.id}`, body) : await post('/api/characters', { ...body, slug: f.slug.value || undefined }); toast('Saved', 'ok'); close(); done(); } catch (e) { fail(e); } } }, 'Save')))], { wide: true });
}
async function history(c) { const { versions } = await get(`/api/characters/${c.id}`); modal((close) => [h('h2', {}, `${c.name_en} — versions`), versions.map((v) => h('div', { class: 'card flat', style: { marginBottom: '8px' } }, h('div', { class: 'row spread' }, badge(`v${v.version_no}`, 'info'), h('span', { class: 'small muted' }, fmtDate(v.created_at))), h('div', { class: 'small', dir: 'auto' }, v.snapshot.features))), h('div', { class: 'row', style: { justifyContent: 'flex-end' } }, h('button', { class: 'btn', onclick: close }, 'Close'))]); }
function prompts(c) { modal((close) => [h('h2', {}, `${c.name_en} — approved prompts`), h('p', { class: 'small muted' }, 'Use these verbatim with any image/video tool so new scenes keep the same look.'), c.approved_prompts.length ? c.approved_prompts.map((p) => h('pre', { class: 'log', style: { whiteSpace: 'pre-wrap' } }, p)) : h('p', { class: 'muted' }, 'None yet.'), h('div', { class: 'row', style: { justifyContent: 'flex-end' } }, h('button', { class: 'btn', onclick: close }, 'Close'))]); }
