import { get, post, put } from '../api.js';
import { h, field, select, toast, fail, badge, usd, progressBar, fmtDate } from '../ui.js';

export async function render(root, S) {
  const c = await get('/api/costs/summary'); const l = c.limits;
  const cfg = S.settings;
  const day = h('input', { type: 'number', min: 0, step: 0.5, value: l.dailyUsd, disabled: !S.can('admin') }); const month = h('input', { type: 'number', min: 0, step: 1, value: l.monthlyUsd, disabled: !S.can('admin') });
  const bar = (spent, lim) => (lim > 0 ? h('div', {}, progressBar(Math.min(1, spent / lim)), h('div', { class: 'small muted' }, `${usd(spent, 4)} of ${usd(lim)}`)) : h('div', { class: 'small' }, `${usd(spent, 4)} — `, badge('no limit set: paid operations are blocked', 'warn')));
  const e = { kind: select(['llm', 'tts', 'image'], 'tts'), provider: select(['anthropic', 'openai', 'azure', 'elevenlabs', 'google', 'espeak', 'local_svg', 'openai_compatible'], 'azure'), tokensIn: h('input', { type: 'number', value: 2500 }), tokensOut: h('input', { type: 'number', value: 6000 }), chars: h('input', { type: 'number', value: 1500 }), images: h('input', { type: 'number', value: 8 }) };
  const out = h('div');
  const estimate = async () => { try { const r = await post('/api/costs/estimate', { kind: e.kind.value, provider: e.provider.value, model: e.kind.value === 'llm' && e.provider.value === 'anthropic' ? 'claude-opus-5-5' : undefined, inputTokens: +e.tokensIn.value, outputTokens: +e.tokensOut.value, chars: +e.chars.value, images: +e.images.value }); out.replaceChildren(h('div', { class: `callout ${r.paid ? 'warn' : 'ok'}` }, h('b', {}, usd(r.estimateUsd, 4)), ' ', r.verified ? badge('verified price', 'ok') : badge('UNVERIFIED price', 'warn'), h('div', { class: 'small' }, r.source || 'free / local'))); } catch (x) { fail(x); } };
  const mp = h('input', { placeholder: 'provider (e.g. Azure)' }); const mo = h('input', { placeholder: 'what for' }); const ma = h('input', { type: 'number', step: 0.01, placeholder: 'USD' });
  root.append(h('div', { class: 'stack-lg' }, h('h1', {}, '🧾 Costs & limits'),
    h('div', { class: 'callout' }, 'Default: everything runs free and local. Paid providers stay ', h('b', {}, 'blocked'), ' until you set a limit, and each paid job needs your explicit confirmation of its estimate. Nothing is ever purchased automatically.'),
    h('div', { class: 'grid g2' },
      h('div', { class: 'card' }, h('h2', {}, 'Spending'), h('div', { class: 'stack' }, h('div', {}, h('b', {}, 'Today'), bar(c.spentTodayUsd, l.dailyUsd)), h('div', {}, h('b', {}, 'This month'), bar(c.spentMonthUsd, l.monthlyUsd)), h('hr'), h('div', { class: 'grid g2' }, field('Daily limit (USD)', day), field('Monthly limit (USD)', month)), h('div', {}, h('button', { class: 'btn primary', disabled: !S.can('admin'), onclick: async () => { try { const r = await put('/api/system/settings', { ...cfg, limits: { dailyUsd: +day.value, monthlyUsd: +month.value } }); S.settings = r.settings; toast('Limits saved', 'ok'); location.reload(); } catch (x) { fail(x); } } }, 'Save limits')), h('p', { class: 'small muted' }, '0 = paid providers blocked. Only the owner can change limits.'))),
      h('div', { class: 'card' }, h('h2', {}, 'Estimator'), h('div', { class: 'stack' }, h('div', { class: 'grid g2' }, field('Type', e.kind), field('Provider', e.provider)), h('div', { class: 'grid g3' }, field('Input tokens', e.tokensIn), field('Output tokens', e.tokensOut), field('Characters (TTS)', e.chars)), field('Images', e.images), h('button', { class: 'btn', onclick: estimate }, 'Estimate'), out, h('p', { class: 'small muted' }, 'Also consider: storage/hosting (local disk is free), music licensing (in-house music is free), and your internet/electricity.'))) ),
    h('div', { class: 'card' }, h('h2', {}, 'Pricing table'), h('div', { class: 'table-wrap' }, h('table', {}, h('thead', {}, h('tr', {}, ['Service', 'Unit', 'Status', 'Source'].map((x) => h('th', {}, x)))), h('tbody', {}, Object.entries(c.pricing).map(([k, v]) => h('tr', {}, h('td', {}, k), h('td', { class: 'small' }, v.unit), h('td', {}, v.verified ? badge(`verified${v.checkedAt ? ' ' + v.checkedAt : ''}`, 'ok') : badge('NOT verified', 'warn')), h('td', { class: 'small', style: { maxWidth: '420px' } }, v.source)))))), h('p', { class: 'small muted' }, 'Only prices checked against a reliable, current source are marked verified. Always confirm on the provider’s pricing page.')),
    h('div', { class: 'card' }, h('h2', {}, 'Recorded usage'), c.recent.length ? h('div', { class: 'table-wrap' }, h('table', {}, h('thead', {}, h('tr', {}, ['When', 'Provider', 'Operation', 'Amount', 'Kind', 'Price'].map((x) => h('th', {}, x)))), h('tbody', {}, c.recent.map((r) => h('tr', {}, h('td', { class: 'small' }, fmtDate(r.ts)), h('td', {}, r.provider), h('td', {}, r.operation), h('td', {}, usd(r.est_cost_usd, 4)), h('td', {}, r.kind), h('td', {}, r.price_verified ? badge('verified', 'ok') : badge('unverified', 'warn'))))))) : h('p', { class: 'muted' }, 'No paid usage recorded.'),
      h('h3', {}, 'Record a cost manually'), h('div', { class: 'row' }, mp, mo, ma, h('button', { class: 'btn', disabled: !S.can('spend'), onclick: async () => { try { await post('/api/costs/manual', { provider: mp.value, operation: mo.value, amountUsd: +ma.value, projectId: S.projectId || undefined }); toast('Recorded', 'ok'); location.reload(); } catch (x) { fail(x); } } }, 'Add')))));
}
