import { get, put } from '../api.js';
import { h, toast, fail, badge, progressBar, num } from '../ui.js';

const stBadge = (s) => ({ search_snippet: badge('checked via official-page snippets 2026-10-10 — verify', 'info'), conflicting: badge('sources conflict — verify', 'bad'), unverified: badge('unverified — verify', 'warn') }[s] || badge(s));

export async function render(root, S) {
  const m = await get('/api/monetization'); const P = m.policy;
  const answers = {}; const sections = {};
  m.items.forEach((i) => { (sections[i.section] = sections[i.section] || []).push(i); });
  const input = (i) => i.kind === 'metric'
    ? h('div', { class: 'row' }, h('input', { type: 'number', min: 0, value: i.value, style: { width: '140px' }, disabled: !S.can('admin'), oninput: (e) => { answers[i.id] = +e.target.value; } }), h('span', { class: 'small muted' }, `target ${num(i.target)}`), i.done && badge('reached', 'ok'), i.status && stBadge(i.status), i.source && h('a', { class: 'small', href: i.source, target: '_blank', rel: 'noopener noreferrer' }, 'source'))
    : h('label', { class: 'check' }, h('input', { type: 'checkbox', checked: i.done, disabled: !S.can('admin'), onchange: (e) => { answers[i.id] = e.target.checked; } }), i.text);
  const up = P.ypp.upcomingChange.value;
  root.append(h('div', { class: 'stack-lg' }, h('h1', {}, '💰 Monetization readiness'),
    h('div', { class: 'callout warn' }, h('b', {}, 'No promises. '), P.disclaimer),
    h('div', { class: 'callout bad' }, h('b', {}, 'Heads-up on timing: '), `YouTube announced higher requirements for new Partner Program applicants from ${up.effective} (${num(up.publicWatchHours365d)} public watch hours in 365 days or ${num(up.publicShortsViews90d)} Shorts views in 90 days). `, stBadge(P.ypp.upcomingChange.status), ' Confirm the exact rules in YouTube Studio → Earn before planning.'),
    h('div', { class: 'grid g3' }, m.concepts.map((c) => h('div', { class: 'card' }, h('h3', {}, c.title), h('p', { class: 'small' }, c.body)))),
    h('div', { class: 'card accent' }, h('div', { class: 'row' }, h('h2', { class: 'grow' }, `Your checklist — ${m.progress}%`), h('div', { style: { width: '240px' } }, progressBar(m.progress / 100))), h('p', { class: 'small muted' }, m.note), Object.entries(sections).map(([sec, items]) => h('div', { style: { marginBottom: '12px' } }, h('h3', {}, sec), items.map((i) => h('div', { class: 'chk', style: { gridTemplateColumns: '1fr' } }, input(i))))),
      h('button', { class: 'btn primary', disabled: !S.can('admin'), onclick: async () => { try { await put('/api/monetization', { answers }); toast('Saved', 'ok'); location.reload(); } catch (e) { fail(e); } } }, 'Save checklist')),
    h('div', { class: 'grid g2' },
      h('div', { class: 'card' }, h('h2', {}, 'YouTube Partner Program'), h('dl', { class: 'kv' }, h('dt', {}, 'Full programme'), h('dd', {}, `${num(P.ypp.full.subscribers.value)} subscribers + ${num(P.ypp.full.publicWatchHours12m.value)} public watch hours (12 months) — or ${num(P.ypp.full.publicShortsViews90d.value)} public Shorts views (90 days)`), h('dt', {}, 'Early access'), h('dd', {}, `${P.ypp.earlyAccess.subscribers.value} subscribers + ${P.ypp.earlyAccess.publicUploads90d.value} uploads (90 days) + ${num(P.ypp.earlyAccess.publicWatchHours12m.value)} hours or ${num(P.ypp.earlyAccess.publicShortsViews90d.value)} Shorts views — fan funding/shopping, not ads`), h('dt', {}, 'Also needed'), h('dd', {}, h('ul', {}, P.ypp.otherRequirements.value.map((x) => h('li', {}, x))))), stBadge(P.ypp.full.subscribers.status), h('p', { class: 'small' }, P.originality.inauthenticContent.value), h('p', { class: 'small' }, P.originality.syntheticDisclosure.value)),
      h('div', { class: 'card' }, h('h2', {}, 'AdSense & getting paid in Iraq'), h('dl', { class: 'kv' }, h('dt', {}, 'Payment methods listed for Iraq'), h('dd', {}, Object.entries(P.payments.iraq.value).map(([k, v]) => badge(`${k}: ${v ? 'yes' : 'no'}`, v ? 'ok' : 'neutral'))), h('dt', {}, 'Payment threshold'), h('dd', {}, `about $${P.payments.thresholdUsd.value} (reporting-currency based)`), h('dt', {}, 'Currency'), h('dd', {}, P.payments.currency.value), h('dt', {}, 'Wire transfers'), h('dd', {}, P.payments.wireDetails.value), h('dt', {}, 'Tax info'), h('dd', {}, P.payments.taxInfo.value), h('dt', {}, 'Identity / PIN'), h('dd', {}, P.payments.identity.value)), stBadge(P.payments.iraq.status), h('p', { class: 'small' }, P.payments.iraq.note, ' ', h('a', { href: P.payments.iraq.source, target: '_blank', rel: 'noopener noreferrer' }, 'source')), h('div', { class: 'callout bad small' }, 'Use your own real identity, address and bank account only. Never use another person’s identity, falsify residency or try to bypass regional restrictions — that can permanently close your AdSense/YouTube accounts.'))),
    h('div', { class: 'card' }, h('h2', {}, 'Made for kids vs monetization'), h('p', { class: 'small' }, P.madeForKids.restrictedFeatures.value.join(' · ')), h('p', { class: 'small' }, P.madeForKids.youtubeKidsApp.value), h('p', { class: 'small' }, P.madeForKids.ownerResponsibility.value), stBadge(P.madeForKids.restrictedFeatures.status)),
    h('div', { class: 'card' }, h('h2', {}, 'YouTube API facts'), h('p', { class: 'small' }, h('b', {}, 'Upload quota: '), P.api.videosInsertQuota.value, ' ', stBadge(P.api.videosInsertQuota.status)), h('p', { class: 'small' }, h('b', {}, 'Unverified API projects: '), P.api.unverifiedProjectPrivate.value, ' ', stBadge(P.api.unverifiedProjectPrivate.status)), h('p', { class: 'small' }, h('b', {}, 'Thumbnails: '), P.api.thumbnails.value, ' ', stBadge(P.api.thumbnails.status)))));
}
